name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
<<<<<<< HEAD:.github/workflows/ci.yml
      - name: Build pb_omni_pid_pursuit_controller
        uses: ros-tooling/action-ros-ci@v0.3
=======
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
>>>>>>> 5e23794 (Update CI (#5)):.github/workflows/build_and_test.yml
        with:
          package-name: pb_omni_pid_pursuit_controller
          target-ros2-distro: humble
